vim.o.termguicolors = true

require("plugins.inpatient")
require("plugins")
require("plugins.autopairs")
require("plugins.autosave")
require("plugins.lsp")
require("plugins.bufferline")
require("plugins.cmp")
require("plugins.colorizer")
require("plugins.gitsigns")
require("plugins.hlslens")
require("plugins.hop")
require("plugins.indent-blankline")
require("plugins.lualine")
require("plugins.material")
require("plugins.navic")
require("plugins.neotest") -- まだ適当
require("plugins.noice")
require("plugins.nvim-tree")
require("plugins.obsidian") -- まだ適当
require("plugins.scrollbar")
require("plugins.telescope")
require("plugins.terminal")
require("plugins.todo-comments")
require("plugins.treesitter")
require("plugins.which-key")
require("plugins.wild")
require("plugins.illuminate")

require("settings")
